### ISSUE TITLE
"error: could not build wheels for scikit-learn" when building image from Dockerfile

### ISSUE THREAD

**Issue by andropar** [gallantlab/headcase-pipeline#11]
Hello,

We're trying to get the headcase pipeline to run using Docker, but we get stuck while building the Dockerfile. Specifically, we get "error: could not build wheels for scikit-learn" while installing from the `requirements.txt`. We started from a fresh clone of the repository and followed instructions in the README. Our docker version is 20.10.7. 

Do you have any ideas about what could cause this issue and how to solve it?

Best,
Johannes

**Comment by andropar** [comment]
The issue for us was that numpy and scipy were installed both via conda and pip, which led to dependency issues. I changed the Dockerfile in my fork, maybe this is worth taking a look at?

**Comment by mvdoc** [comment]
This issue should be solved by #12.
